pipeline {
    agent any

    tools {
        maven 'Maven'   // Make sure you configured Maven in Jenkins Global Tool Configuration
        jdk 'JDK11'     // (Optional) Configure JDK if needed
    }

    stages {
        stage('Maven Clean') {
            steps {
                dir("CuraHealthcareProject") {  // Go inside project folder
                    bat 'dir'                   // Just to check files
                    bat 'mvn clean'             // Use bat for Windows, sh for Linux
                }
            }
        }

        stage('Maven Test') {
            steps {
                dir("CuraHealthcareProject") {
                    bat 'mvn test'
                }
            }
        }
    }

    post {
        always {
            junit 'CuraHealthcareProject/target/surefire-reports/*.xml'  // Publish test results
        }
    }
}
