pipeline {
    agent any

    tools {
        maven 'Maven'   // Make sure Maven is configured in Global Tool Configuration
        jdk 'JDK11'     // Ensure JDK11 is configured too
    }

    stages {
        stage('Maven Clean') {
            steps {
                dir("CuraHealthcareProject") {
                    bat 'mvn clean'
                }
            }
        }

        stage('Maven Test') {
            steps {
                dir("CuraHealthcareProject") {
                    bat 'mvn test'
                }
            }
        }
    }

    post {
        always {
            // Publish JUnit test reports
            junit 'CuraHealthcareProject/target/surefire-reports/*.xml'
        }

        failure {
            // Send email when build fails
            emailext(
                to: 'mahmankar333@gmail.com',
                subject: "Build Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    <h2 style="color:#d9534f;">Build Failure Notification</h2>
                    Hello Mahii,<br><br>
                    The Jenkins build <b>${env.JOB_NAME} #${env.BUILD_NUMBER}</b> has <b>FAILED</b>.<br><br>
                    
                    <b>Build Details:</b><br>
                    - Job: ${env.JOB_NAME}<br>
                    - Build Number: ${env.BUILD_NUMBER}<br>
                    - URL: <a href='${env.BUILD_URL}'>Click here to view logs</a><br><br>
                    
                    <b>Next Steps:</b><br>
                    Please review the logs and test results.<br><br>
                    
                    Regards,<br>
                    Jenkins CI/CD
                """,
                mimeType: 'text/html'
            )
        }
    }
}
